server:
  port: 8080

spring:
  application:
    name: team-jeopardy

team-jeopardy:
  sample-code-path: ../samples/sample-reactor
  sample-gradle-path: ../samples/sample-gradle
  sample-vue-path: ../samples/sample-vue
  allowed-origins: "*"
  max-teams: 6
  max-players-per-team: 8
  buzz-lock-ms: 8000

logging:
  level:
    com.jmjava.teamjeopardy: INFO
